'use strict'

module.exports = {
  API_KEY: "YOUR_API_KEY",
  AUTH_DOMAIN: "YOUR_AUTH_DOMAIN",
  DATABASE_URL: "YOUR_DATABASE_URL",
  STORAGE_BUCKET: "YOUR_STORAGE_BUCKET",
  MESSAGING_SENDER_ID: "YOUR_SENDER_ID"
}